# Generated by Django 3.2.7 on 2021-09-25 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='date_entered',
            field=models.DateTimeField(default=datetime.date(2021, 9, 24)),
            preserve_default=False,
        ),
    ]
